version: '3.7'
services:
  web:
    image: sajalshres/boggle-game:latest
    restart: on-failure
    ports:
      - '8080:8080'
      - '8081:8081'
    command: "rake start"
    container_name: boogle_web
