version: '3.7'
services:
  web:
    image: sajalshres/boggle-game:latest
    restart: on-failure
    ports:
      - '3000:3000'
      - '3001:3001'
    command: "rake start"
    container_name: boggle_web
